# Generated by Django 5.2.12 on 2026-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Owiye Sylvia', max_length=100)),
                ('title', models.CharField(default='Full-stack Developer', max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
