# Generated by Django 5.2.12 on 2026-04-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_delete_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Programming', 'Programming Languages'), ('Frontend', 'Frontend Development'), ('Backend', 'Backend Development'), ('Databases', 'Databases'), ('Collaboration', 'Version Control & Collaboration'), ('Tools', 'Tools & Technologies')], max_length=50)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
